/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemsIndexRouteImport } from './routes/systems.index'
import { Route as LogsIndexRouteImport } from './routes/logs.index'
import { Route as SystemsSlugRouteImport } from './routes/systems.$slug'
import { Route as LogsSlugRouteImport } from './routes/logs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSlugRoute = SystemsSlugRouteImport.update({
  id: '/systems/$slug',
  path: '/systems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsSlugRoute = LogsSlugRouteImport.update({
  id: '/logs/$slug',
  path: '/logs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs/$slug': typeof LogsSlugRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/logs/': typeof LogsIndexRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs/$slug': typeof LogsSlugRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/logs': typeof LogsIndexRoute
  '/systems': typeof SystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs/$slug': typeof LogsSlugRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/logs/': typeof LogsIndexRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logs/$slug' | '/systems/$slug' | '/logs/' | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logs/$slug' | '/systems/$slug' | '/logs' | '/systems'
  id:
    | '__root__'
    | '/'
    | '/logs/$slug'
    | '/systems/$slug'
    | '/logs/'
    | '/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsSlugRoute: typeof LogsSlugRoute
  SystemsSlugRoute: typeof SystemsSlugRoute
  LogsIndexRoute: typeof LogsIndexRoute
  SystemsIndexRoute: typeof SystemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$slug': {
      id: '/systems/$slug'
      path: '/systems/$slug'
      fullPath: '/systems/$slug'
      preLoaderRoute: typeof SystemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$slug': {
      id: '/logs/$slug'
      path: '/logs/$slug'
      fullPath: '/logs/$slug'
      preLoaderRoute: typeof LogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsSlugRoute: LogsSlugRoute,
  SystemsSlugRoute: SystemsSlugRoute,
  LogsIndexRoute: LogsIndexRoute,
  SystemsIndexRoute: SystemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
